### ISSUE TITLE
Ordering for MD files Not intuitive 

### ISSUE THREAD

**Issue by gabalicious** [engineerkit/engineerkit#48]
There is numbering for files exercises and modules. So what happens is its listed in alphabetical order.  I would expect that there be numbers in front of the MD file names so I know what order i'm supposed to go through it without needing to think.   I don't feel like thinking more that I have to.

**Comment by chandlerroth** [comment]
> There is numbering for files exercises and modules. So what happens is its listed in alphabetical order. I would expect that there be numbers in front of the MD file names so I know what order i'm supposed to go through it without needing to think. I don't feel like thinking more that I have to.

Appreciate you sharing this! Originally we had numbers, but then realized that we didn't want this to be a linear "curriculum" experience, so that you can follow your curiosity in any order you like. Although I think it would be good to press your pain point here -- would you say that discoverability was an issue when going through each skill?
